### ISSUE TITLE
Misleading documentation for HtmlCrawlerSubscriber

### ISSUE THREAD

**Issue by aleksblendwerk** [terminal42/escargot#15]
The documentation states:

> The `HtmlCrawlerSubscriber` [...] sets `CrawlUri` tags if the link points to any host which is not part of the `BaseUriCollection`.

but I can't see it doing that anywhere, or am I missing something?

And by the way: I am not saying it should either, as I would prefer handling that in a dedicated Subscriber anyway (e.g. I might want to allow subdomains of the given Base Uri but no completely external URLs).

And to derail this even further: it might be nice to ship Escargot with a subscriber that can handle a few common cases regarding allowed or forbidden domains:

- all URLs 
- only domains specified as Base Uris 
- only domains specified as Base Uris and their subdomains

could be good presets...

**Comment by Toflar** [comment]
Right, docs fixed in d6d9305a6ceb972e4e434d4b127ab4ac645823aa.

> could be good presets...

I did think about this for a pretty long time and it's something that I strongly disagree with.
Providing configurable, reusable presets can overcomplicate things a lot. If you've ever worked with Symfony Security you will know exactly what I'm talking about.
Writing a subscriber that filters for only URIs that match a certain domain requires 3 lines of code. It keeps the library simple and concise.

That being said, we can always add more helper methods to the `BaseUriCollection` class which already provides a `containsHost()` method. PR's are welcome :)
